### ISSUE TITLE
qdrant e Dify não instalam na contabo

### ISSUE THREAD

**Issue by int211** [oriondesign2015/SetupOrion#23]
Ola, man o qdrant não instala de jeito nenhum, ja tentei em outra VPS mas não vai, tem algum macete?
Percebi que o pessoal tb esta com muita dificuldade no Dify, se puder dar um norte agradeço, valeu.

**Comment by oriondesign2015** [comment]
Salve, só seguir este video que é sucesso: https://youtu.be/urRBizeIFjU
