### ISSUE TITLE
Erro senha portainer

### ISSUE THREAD

**Issue by diegosayron** [oriondesign2015/SetupOrion#29]
**Versão do Script**: 2.5.0
**Case:**
Depois de instalar o traefik e portainer (senha criada com sucesso), tentando instalar o chatwoot, informa que a partir da versão 2.5.0 é solicitada a senha do portainer. 
Nesse momento, digito as credenciais mas informa credenciais incorretas.

**Tentativas:**
- Criar novo usuário e senha (sem caracteres especiais, tamanho sempre >= 12) - sem sucesso
- Alterar senha (tamanho >= 12): sem sucesso

**Comment by emanuelbernardes** [comment]
A URL foi informada da forma correta @diegosayron ?

**Comment by val-leite** [comment]
Estou com mesmo problema e informei todas as informações corretas.

**Comment by oriondesign2015** [comment]
@diegosayron @val-leite 

Junte-se aos nossos grupos no WhatsApp e troque conhecimento ou tire suas dúvidas com nossos membros:

Grupo #01 - SetupOrion
https://oriondesign.art.br/whatsapp1

Grupo #02 - 🆕 SetupOrion
https://oriondesign.art.br/whatsapp2
