### ISSUE TITLE
Preciso instalar a versão mais recente do supabase, supabase studio

### ISSUE THREAD

**Issue by codefutura** [oriondesign2015/SetupOrion#32]
Atualmente tenho problemas ao usar o tempo real com a versão que estão instalando, a versão recente inclui o painel em tempo real que permite ativá-lo.
dokerhub docker pull supabase/studio:20240520-0259321
Posso alterar todas as versões das imagens na instalação do supabase?

**Comment by oriondesign2015** [comment]
Junte-se aos nossos grupos no WhatsApp e troque conhecimento ou tire suas dúvidas com nossos membros:

Grupo #01 - SetupOrion
https://oriondesign.art.br/whatsapp1

Grupo #02 - 🆕 SetupOrion
https://oriondesign.art.br/whatsapp2
