### ISSUE TITLE
Evolutionapi Cannot GET /manager

### ISSUE THREAD

**Issue by tonnybarros** [oriondesign2015/SetupOrion#36]
Olá pessoal, ótimo instalador, parabens!

Tentei instalar o evolution api, informeio domínio certinho, deu como instalado, mas o manager quando abre, aparece
Cannot GET /manager

**Comment by oriondesign2015** [comment]
Junte-se aos nossos grupos no WhatsApp e troque conhecimento ou tire suas dúvidas com nossos membros:

Grupo #01 - SetupOrion
https://oriondesign.art.br/whatsapp1

Grupo #02 - 🆕 SetupOrion
https://oriondesign.art.br/whatsapp2
