### ISSUE TITLE
instalação Woofed 

### ISSUE THREAD

**Issue by igrdevl** [oriondesign2015/SetupOrion#42]
Woofed não instala, fica na tela de instalação eternamente.

![image](https://github.com/user-attachments/assets/f40daff1-9de9-41cf-abfd-20d91f362a10)

**Comment by oriondesign2015** [comment]
Saudações, me chama no pv do whatsapp: +5511973052593 ou entre em nossa comunidade para um suporte mais efetivo:
https://oriondesign.art.br/whatsapp1 ou https://oriondesign.art.br/whatsapp2
