### ISSUE TITLE
adição de ferramentas

### ISSUE THREAD

**Issue by tykocompany** [oriondesign2015/SetupOrion#44]
gostaria de saber como faço para incluir ferramentas aqui, quero incluir o Whaticket SaaS.

**Comment by oriondesign2015** [comment]
Olá, tudo bem?

Agradecemos o incentivo de querer adicionar uma nova ferramenta ao nosso setup.

Basicamente para você adicionar algo ao mesmo você precisa de criar uma função dentro do nosso [script](https://github.com/oriondesign2015/SetupOrion/blob/main/SetupOrion), seguindo a estrutura do mesmo, para realizar a instalação/configuração do mesmo (precisa de conhecimento em bash para isso).

Já gostaria de expressar que no momento não temos interesse no Whaticket SaaS devido não ser uma solução oficial da propria equipe do Whaticket e não termos o controle de correções/verificações que se ocorre com o mesmo.

Mas você pode criar um Fork do Setup e adicionar em uma versão modificada do mesmo para o seu proprio consumo =D

Desde já, agradecemos o intuito e por usar nossa ferramenta.

Equipe **OrionDesign**
