### ISSUE TITLE
Dify apresenta 502 bad gateway no serviço da API

### ISSUE THREAD

**Issue by tiagotalbuquerque** [oriondesign2015/SetupOrion#48]
Amigos, tentei instalar o Dify mas parece que a chamada na API sempre vai para um IP de um container diferente do que está servindo a API.  

https://docs.dify.ai/learn-more/faq/self-host-faq#id-20.-502-bad-gateway

Tentei a solução manual indicada mas ao recarregar o nginx no container, o ip fica mudando. 

Acredito que está faltando atualizar alguma configuração na receita do stack para deixar mapeado corretamente pq o nginx direcionando o serviço pra o container errado.

Obrigado.

**Comment by oriondesign2015** [comment]
Salve. Segue o guia abaixo:

No terminal da vps digita:

`rm -r dify nginx`

`git clone https://github.com/langgenius/dify.git`

`sudo mv /root/dify/docker/nginx /root/nginx`

`rm -r dify`

E deleta os *Containers* do Dify no Portainer..
Após isso aguarde uns 30 segundos a 1 minuto e tente acessar novamente.

Junte-se aos nossos grupos no WhatsApp e troque conhecimento ou tire suas dúvidas com nossos membros:

Grupo #01 - SetupOrion
https://oriondesign.art.br/whatsapp1

Grupo #02 - 🆕 SetupOrion
https://oriondesign.art.br/whatsapp2

**Comment by tiagotalbuquerque** [comment]
Agradeço sua ajuda amigo, infelizmente não funcionou. 

Cheguei até repetir o processo esperando intervalos de tempo mais longos mas não funcionou.

**Comment by oriondesign2015** [comment]
Nos chame no WhatsApp 5511973052593 que damos uma olhada e corrigimos isso para ti.
