### ISSUE TITLE
Erro ao instalar o EvolutionApi V2

### ISSUE THREAD

**Issue by adelimateus** [oriondesign2015/SetupOrion#50]
Quando já tenho instalado o EvolutionApi V1 e tento instalar o EvolutionApi v2 dá erro pois já existe um Stack chamado evolution.

Sugiro alterar o stack do EvolutionV2 par --> evolution2 de fomr a a ter as duas stacks como opção.

**Comment by oriondesign2015** [comment]
Olá, tudo bem?

Após a atualização do dia 12/08/2024 (segunda-feira), a opção **[ 3 ] - Evolution API**, que anteriormente instalava a Evolution v1, agora instala exclusivamente a Evolution v2. O objetivo dessa mudança é incentivar a migração para a Evolution 2.

Se você já tem a Evolution v1 instalada e deseja continuar usando-a, é necessário remover a stack da Evolution atual e realizar uma nova instalação da Evolution v1, conforme recomendado pelo próprio Davidson, criador da Evolution API.

No entanto, se você pretende manter a Evolution v1 instalada e também instalar a Evolution 2, sem perder o acesso à v1, você pode fazê-lo através do Setup. Siga a nota de atualização e use o comando `evolution.v2` para instalar a versão 2. Da mesma forma, se já tiver a Evolution v2 e quiser instalar a Evolution v1, use o comando `evolution.v1`.

Sobre o banco de dados, o Setup foi projetado para instalar a aplicação uma única vez. Caso precise ter duas instâncias da Evolution v2 (uma instalada pela opção 3 e outra pelo comando `evolution.v2`), será necessário ajustar manualmente a stack para evitar problemas.

Essas mudanças visam garantir que todas as automações e funcionalidades sejam compatíveis com o padrão do Setup para todos os usuários.

Agradecemos o Feedback

Junte-se aos nossos grupos no WhatsApp e troque conhecimento ou tire suas dúvidas com nossos membros:

Grupo #01 - SetupOrion
https://oriondesign.art.br/whatsapp1

Grupo #02 - 🆕 SetupOrion
https://oriondesign.art.br/whatsapp2
