### ISSUE TITLE
Minio Erro

### ISSUE THREAD

**Issue by tykocompany** [oriondesign2015/SetupOrion#58]
Estou tentando fazer login no Minio, tenho uma VPS própria que está configurada em IPv6, não sei se é por conta disso, mas como não tenho IPv4 público, fiz tudo pelo IPv6 mesmo. Tentei em 5 instancias diferentes e todas deram o mesmo problema, segue abaixo o erro.

![image](https://github.com/user-attachments/assets/efbad2b1-2b21-4ff1-b29d-1cc54e4056cb)

**Comment by tykocompany** [comment]
Tive um problema com o N8N também, resolvi voltando a versão da imagem, mas pelo que vi do Minio é a mesma versão que tinha em outra VPS.

**Comment by oriondesign2015** [comment]
Olá, se você abrir o Portainer > Stack > Minio > Editor, você vera escrito na linha 23 o que é para fazer nesse caso de "erro".

```
## Url do minio
- MINIO_BROWSER_REDIRECT_URL=https://$url_minio ## Url do minio
- MINIO_SERVER_URL=https://$url_s3 ## Url do s3 | Comente esta linha caso tiver erro ao fazer login
```

Como descrito, você precisa Comentar esta linha (ou apagar) caso tiver erro ao fazer login.
