### ISSUE TITLE
Erro no Login Typebot - "Não autorizado" "As inscrições estão desativadas."

### ISSUE THREAD

**Issue by FabiolaBaani** [oriondesign2015/SetupOrion#7]
![image](https://github.com/oriondesign2015/SetupOrion/assets/33585451/32c97565-667d-4b2d-8de7-981b7e901ea8)

Estou recebendo essa mensagem quando tento fazer login no builder

**Comment by oriondesign2015** [comment]
Olá @FabiolaBaani, tudo bem?
Esse erro acontece por dois possíveis motivos, mas ambos envolve seu SMTP:

**1- Dados do SMTP errados**
Pode ser que na hora de preencher os dados, você tenha coloca o "Host SMTP"/"Porta SMTP"/"Email"/"Senha do email" errados.
Isso é comum e para resolver, basta executar novamente nosso instalador do typebot com o seguinte comando:
```
cd && cd SetupOrion && ./typebot.io
```
Dai você preenche as informações novamente (todas) e ele já vai rebuildar seu Typebot com os novos dados. Caso você veja que realmente não era os dados preenchidos (mesmo conferindo os dados) pode ser que os dados que você possua de SMTP estejam defasados ou errados. Você pode realizar um teste de SMTP através do site: https://www.gmass.co/smtp-test
Se através do teste der sucesso, ai vai ser o segundo caso que vou citar abaixo, mas caso der falha, recomendo procurar os dados SMTP com o suporte do seu email.

**2- VPS com Bloqueio de envio de emails**
Infelizmente algumas VPS bloqueiam o uso da porta 21 (se não me engano) que é utilizada para o envio de emails, por conta de algumas pessoas que pegam a vps e fazem Spam. Devido a isso você precisa de realizar o contato com a VPS que esta usando e solicitar a liberação. Geralmente é bem rápido mas depende de cada VPS.

Todavia se precisar de um auxilio mais próximo, pode me chamar no Whatsapp: 11973052593

**Comment by FabiolaBaani** [comment]
Oiiiii funcionou, loguei e já até criei um fluxo a partir dos modelos pra
testar, agora o erro que aparece quando escolho configurações é: Error!
Couldn't initiate the chat

Em qui, 9 de nov de 2023 01:54, oriondesign2015 ***@***.***>
escreveu:

**Comment by oriondesign2015** [comment]
Olá @FabiolaBaani, tudo bem?

Bom esse erro geralmente acontece por 2 motivos, ou é porque na hora da instalação, o registro DNS "storage" não tinha se propagado completamente ou foi preenchido errado.

Dois testes que você pode realizar é:

1- Vá no seu terminal e digita o seguinte código:
```
cd && cd typebot.io && docker-compose up -d
```

Após terminar de carregar tenta acessar novamente o painel e vê se o problema foi corrigido.

2- Caso o passo anterior falhou, você pode abrir o arquivo docker-compose.yml digitando:
```
cd && cd typebot.io && nano docker-compose.yml
```
Procura pela parte que contem a url do seu storage, e verifica se esta preenchido corretamente, lembrando que não pode ter `https://` nem `/` no final. o arquivo vai parecer +- com isso:
![image](https://github.com/oriondesign2015/SetupOrion/assets/139019565/6260bb6f-1039-45d9-8f7e-9aac3786d6bc)
e você encontrará dois locais com o link do seu storage. caso não tiver preenchaos.
deve ficar +- assim:
![image](https://github.com/oriondesign2015/SetupOrion/assets/139019565/10d15a3d-5518-444b-ae2f-6dd0914635b0)

Todavia se precisar de um auxilio mais próximo, pode me chamar no Whatsapp: 11973052593

Aguardo uma atualização do assunto =D

**Comment by FabiolaBaani** [comment]
Consegui!!!
Reinstalei tudo e funcionou perfeitamente 😍

Em qui, 9 de nov de 2023 13:01, oriondesign2015 ***@***.***>
escreveu:

**Comment by FabiolaBaani** [comment]
Solucionado perfeitamente!!!
