### ISSUE TITLE
Erro ao instalar chatwoot

### ISSUE THREAD

**Issue by lukasabino** [oriondesign2015/SetupOrion#8]
Já testei com 3 instalações, tanto em container, vps e maquina dedicada, todas me retornam o seguinte erro:

Some error has occured. Check '/var/log/chatwoot-setup.log' for details.
Could not find rails-7.0.8, bootsnap-1.16.0, acts-as-taggable-on-9.0.1, jbuilder-2.11.5, kaminari-1.2.2, responders-3.1.1, rest-client-2.1.0, valid_email2-4.0.6, commonmarker-0.23.10, gmail_xoauth-0.4.2, aws-sdk-s3-1.122.0, google-cloud-storage-1.44.0, image_processing-1.12.2, pg-1.5.3, redis-namespace-1.10.0, activerecord-import-1.4.1, dotenv-rails-2.8.1, puma-6.3.1, webpacker-5.4.4, devise-4.9.3, devise_token_auth-1.2.1, administrate-0.19.0, administrate-field-active_storage-0.4.2, administrate-field-belongs_to_search-0.8.0, twilio-ruby-5.77.0, twitty-0.1.5, slack-ruby-client-2.2.0, google-cloud-dialogflow-v2-0.23.0, google-cloud-translate-v3-0.6.0, ddtrace-1.11.1, elastic-apm-4.6.2, newrelic-sidekiq-metrics-1.6.2, scout_apm-5.3.3, sentry-rails-5.13.0, sentry-sidekiq-5.13.0, sidekiq-cron-1.11.0, fcm-1.0.8, hairtrigger-1.0.0, procore-sift-1.0.0, pg_search-2.3.6, lograge-0.14.0, omniauth-oauth2-1.8.0, audited-5.4.1, omniauth-google-oauth2-1.1.1, omniauth-rails_csrf_protection-1.0.1, neighbor-0.2.3, reverse_markdown-2.1.1, informers-0.2.0, annotate-3.2.0, letter_opener-1.8.1, scss_lint-0.60.0, web-console-4.2.1, stackprof-0.2.25, meta_request-0.7.4, database_cleaner-2.0.2, byebug-11.1.3, debug-1.8.0, factory_bot_rails-6.2.0, listen-3.8.0, rspec-rails-6.0.2, rubocop-1.50.2, rubocop-performance-1.17.1, rubocop-rails-2.19.1, rubocop-rspec-2.21.0, seed_dump-3.3.1, spring-watcher-listen-2.1.0, actioncable-7.0.8, actionmailbox-7.0.8, actionmailer-7.0.8, actionpack-7.0.8, actiontext-7.0.8, actionview-7.0.8, activejob-7.0.8, activerecord-7.0.8, activestorage-7.0.8, railties-7.0.8, msgpack-1.7.0, kaminari-actionview-1.2.2, kaminari-activerecord-1.2.2, http-cookie-1.0.5, mail-2.8.1, aws-sdk-kms-1.64.0, nokogiri-1.15.4-x86_64-linux, google-apis-iamcredentials_v1-0.17.0, google-apis-storage_v1-0.19.0, google-cloud-core-1.6.0, googleauth-1.5.2, ruby-vips-2.1.4, nio4r-2.5.9, bcrypt-3.1.19, jquery-rails-4.6.0, sassc-rails-2.1.2, gapic-common-0.18.0, google-cloud-location-0.4.0, libddwaf-1.8.2.0.0-x86_64-linux, http-5.1.1, fugit-1.9.0, numo-narray-0.9.2.1, onnxruntime-0.7.6-x86_64-linux, sass-3.7.4, bindex-0.8.1, database_cleaner-active_record-2.1.0, rb-inotify-0.10.1, rubocop-capybara-2.18.0, websocket-driver-0.7.6, rails-dom-testing-2.2.0, rails-html-sanitizer-1.6.0, domain_name-0.5.20190701, racc-1.7.3, google-apis-core-0.11.0, ffi-1.15.5, sassc-2.4.0, sprockets-rails-3.4.2, googleapis-common-protos-1.4.0, llhttp-ffi-0.4.0, sass-listen-4.0.0, loofah-2.21.4, unf-0.1.4, ffi-compiler-1.0.1, unf_ext-0.0.8.2 in locally installed gems
Run `bundle install` to install missing gems.
./chatwoot.sh: line 305: cwctl: command not found
Failed to restart chatwoot.target: Unit chatwoot.target not found.
psql: error: FATAL:  database "chatwoot_production" does not exist

![image](https://github.com/oriondesign2015/SetupOrion/assets/70410692/1a40a532-77b1-4f6c-ada6-8d2e4785ed74)

**Comment by oriondesign2015** [comment]
@lukasabino Opa, tudo bem? Me passa algumas informações por favor:
1- Qual é a empresa que você comprou a vps? (Hetnerz, Contabo, Digital Ocean, Oracle, Google...)
2- Qual a configuração da sua VPS? (Gb Ram, vCores, Armazenamento..)
3- Qual o sistema operacional que esta usando na VPS? (Ubuntu 20.04, Ubuntu 22.0, Debian..)
4- Você criou os registros DNS através da onde? (Cloudflare, Hostinger, RegistroBR...)
 
 Com essas informações eu poderei ajuda-lo melhor.

**Comment by lukasabino** [comment]
Opa!

A VPS está num servidor próprio, via Proxmox.
Coloquei o básico 8Gb Ram + 4vCores + Ubuntu 20.04.
Usei CloudFlare para apontar o domínio

![image](https://github.com/oriondesign2015/SetupOrion/assets/70410692/fbf69141-e4db-4369-a33e-c7f21fa30f4a)

**Comment by oriondesign2015** [comment]
Desculpa a demora, man, creio que não vá rodar por conta da virtualização, nosso instalador é recomendado para Servidores da Contabo ou Hetnerz
