### ISSUE TITLE
Atualização dos programas

### ISSUE THREAD

**Issue by FabiolaBaani** [oriondesign2015/SetupOrion#9]
depois de instalados (instalador bom demais inclusive) como faço para atualizar algum dos programas, rodo o instalador de novo?

**Comment by oriondesign2015** [comment]
@FabiolaBaani Tudo bem? Se estiver usando o instalador 1, sim, se estiver usando meu novo instalador, eu mostro no final do video. Caso esteja ainda com o primeiro instalador, recomendo bastante partir para o novo. Você pode encontrar mais informações sobre ele em meu canal youtube.com/oriondesign_oficial
